language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- polymer test --plugin sauce --job-name "history-list-items:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: hIasdN71VLyn3Gg8NuklkLhxph1b0JM0EMs0N0Du6gT/h+wupjPSkeO+GnSk7/WnFuRgdayRgzmhujsZAabF4rH6A1ODUg+xifz1srxYpzyqj0IKyNiqm/mnkeLJ6sLrjLwzdpri3OwmSStMUHLvWwiVNaeJEm9HUgLFmp6MGnEg8fbdKDmoktlaYBwKnOL9TZjOTlwrW7zhgYPQVRnPdT2Uxe4v2HI2/CaMZl/KY8U8GjTN7VgXER/x/rdBiANLOXhXE6bBd8V/xk0SBweVtpigmqYJZxGwPWKqiwKVtLodhwDPX7h7e1V85jP81nkEB5Af9y+1Sz5RzFtNoMG7qOxT0jfmzmWaaGySXpXZe7nmEKqXr68M0I0vNadANFz6BpKJUT59Dk+0DGRFfmp6UrCdlqyTaijUOQr6I1kb13o8bDKtTEP+p9AE9ZLAPYAZ5ImBTF4Xdn3JG7IIm+LNsuzubmJBS63/aVQlubyOiSMZaCsjBr6o7DL4DEAxmi9vltg7kTHKkc17l6lbwFikoKZ2HL2fkOwCqXUNbr/CP5Hf0vwr/2MxB+3nKsC11fP1aJaM2FQmy/2bV+JDuJHMas13Iav8MYSLYoiEbPJLIR1Uj61kacuLJY3/wH36/jTmIdEIC/aEyLjYWGyKjjmpV3ab4kB02PjZ5H35GG38y4Q=
  - secure: tiKC617IKdnWYVXqEdgtDH/iBgqE2F3q0DQkCPwm3mKgCikC7gEVBR6ikyDh3kce8CpBtNhIaYcWoLNJdMigfTrm1id8pnticim/cUx0LJVwnIHyJXiUi1ZZeuPko0Q1X+y8lkxnrTAmkNpZp1EO9MaVDZ3GsKC+Hx7nsvWWaBkiGMmWu1axkg+tT2/fCMX3JqUKvwe1G9+RcNoNL1JM00PdFajRGWrYLLhdEiw5c5HSRYqS4Tpiw/NGTM4GpAI4MjBc9toCcR9gFOJTBQoSF5kmcUgzvVrD9que1+QcWp1Qkw3Z1xx7feX5Le0madsPGi41yPIKA3n00p6dAN5Jwy9prk0N6uyl28xDlHLP4vRyH2hyXvfYhm40i7/dKWquqEJjrk3TegFpdEqOUEIlHfxuNAv1B9cvAwJ+juTwQInQuk9J5SoIwiPylLJM91gUP8HY1iQQxCwQnjYzvcMtpM6TTMKytoQKAz47GmC5NDbMQFh/kk0SyytHDZjuoY0WR+t2fabd/Ngm4WNnBVLP3ijh9J7MqYCNYvWGttuqHsTPfhFQ7/RiYZITJcan43VvdW0eVAe7gqsZqUK38b67xhDiuM75D8zC2Ygcxp3BU0IhH2OJ6UMIqhqY2+NhtfYGXVPLw44p4zCT0Z7JgPpvoTB0CwEE2nDqo8yLwJnV0x8=
